import React, { useMemo, useState } from 'react';
import * as HI from 'hugeicons-react';
import { cn } from '../utils/cn';

const RECENT_ICONS_STORAGE_KEY = 'dayline:recent-icons';
const MAX_RECENT_ICONS = 12;

export const ALL_ICONS: Record<string, React.ElementType> = {
  Search: HI.Search01Icon as React.ElementType,
  Shuffle: HI.ShuffleIcon as React.ElementType,
  X: HI.Cancel01Icon as React.ElementType,
  Home: HI.Home01Icon as React.ElementType,
  Bell: HI.Notification01Icon as React.ElementType,
  Settings: HI.Settings01Icon as React.ElementType,
  Plus: HI.Add01Icon as React.ElementType,
  MessageSquare: HI.Message02Icon as React.ElementType,
  Calendar: HI.Calendar01Icon as React.ElementType,
  Inbox: HI.InboxIcon as React.ElementType,
  Pencil: HI.PencilEdit01Icon as React.ElementType,
  CheckCircle2: HI.CheckmarkCircle02Icon as React.ElementType,
  Target: HI.Target01Icon as React.ElementType,
  Layers: HI.Layers01Icon as React.ElementType,
  Activity: HI.Activity01Icon as React.ElementType,
  Smile: HI.SmileIcon as React.ElementType,
  Stethoscope: HI.StethoscopeIcon as React.ElementType,
  Book: HI.Book01Icon as React.ElementType,
  Feather: HI.FeatherIcon as React.ElementType,
  Folder: HI.Folder01Icon as React.ElementType,
  Dumbbell: HI.Dumbbell01Icon as React.ElementType,
  Utensils: HI.Restaurant01Icon as React.ElementType,
  ShoppingCart: HI.ShoppingCart01Icon as React.ElementType,
  Bookmark: HI.Bookmark01Icon as React.ElementType,
  Plane: HI.Airplane01Icon as React.ElementType,
  Library: HI.LibraryIcon as React.ElementType,
  ShoppingBag: HI.ShoppingBag01Icon as React.ElementType,
  MonitorPlay: HI.PlayCircle02Icon as React.ElementType,
  Users: HI.UserGroupIcon as React.ElementType,
  File: HI.File01Icon as React.ElementType,
  LayoutDashboard: HI.DashboardSquare01Icon as React.ElementType,
  Box: HI.DeliveryBox01Icon as React.ElementType,
  Database: HI.DatabaseIcon as React.ElementType,
  Plug: HI.Plug01Icon as React.ElementType,
  Clock: HI.Clock01Icon as React.ElementType,
  FileText: HI.File02Icon as React.ElementType,
  Lock: HI.LockIcon as React.ElementType,
  Shield: HI.Shield01Icon as React.ElementType,
  Wallet: HI.Wallet01Icon as React.ElementType,
  Download: HI.Download01Icon as React.ElementType,
  Upload: HI.Upload01Icon as React.ElementType,
  Star: HI.StarIcon as React.ElementType,
  Heart: HI.FavouriteIcon as React.ElementType,
  Zap: HI.ZapIcon as React.ElementType,
  Flame: HI.FireIcon as React.ElementType,
  Cloud: HI.CloudIcon as React.ElementType,
  Sun: HI.Sun01Icon as React.ElementType,
  Moon: HI.MoonIcon as React.ElementType,
  Coffee: HI.Coffee01Icon as React.ElementType,
  Pizza: HI.Pizza01Icon as React.ElementType,
  Music: HI.MusicNote01Icon as React.ElementType,
  Camera: HI.Camera01Icon as React.ElementType,
  Video: HI.Video01Icon as React.ElementType,
  Map: HI.MapsIcon as React.ElementType,
  Globe: HI.GlobeIcon as React.ElementType,
  Navigation: HI.Navigation01Icon as React.ElementType,
  Anchor: HI.AnchorIcon as React.ElementType,
  Briefcase: HI.Briefcase01Icon as React.ElementType,
  GraduationCap: HI.CapIcon as React.ElementType,
  Trophy: HI.Award01Icon as React.ElementType,
  Medal: HI.Medal01Icon as React.ElementType,
  Smartphone: HI.SmartPhone01Icon as React.ElementType,
  Laptop: HI.LaptopIcon as React.ElementType,
  Tablet: HI.Tablet01Icon as React.ElementType,
  Cpu: HI.CpuIcon as React.ElementType,
  HardDrive: HI.HardDriveIcon as React.ElementType,
  Mouse: HI.Mouse01Icon as React.ElementType,
  Keyboard: HI.KeyboardIcon as React.ElementType,
  Mail: HI.Mail01Icon as React.ElementType,
  Phone: HI.CallIcon as React.ElementType,
  Share2: HI.Share01Icon as React.ElementType,
  Link: HI.Link01Icon as React.ElementType,
  Hash: HI.HashtagIcon as React.ElementType,
  AtSign: HI.AtIcon as React.ElementType,
  AlertCircle: HI.AlertCircleIcon as React.ElementType,
  HelpCircle: HI.HelpCircleIcon as React.ElementType,
  Info: HI.InformationCircleIcon as React.ElementType,
  Check: HI.Tick01Icon as React.ElementType,
  AlertTriangle: HI.Alert01Icon as React.ElementType,
  ArrowUp: HI.ArrowUp01Icon as React.ElementType,
  ArrowDown: HI.ArrowDown01Icon as React.ElementType,
  ArrowLeft: HI.ArrowLeft01Icon as React.ElementType,
  ArrowRight: HI.ArrowRight01Icon as React.ElementType,
  Maximize: HI.Maximize01Icon as React.ElementType,
  Minimize: HI.Minimize01Icon as React.ElementType,
  RefreshCw: HI.RefreshIcon as React.ElementType,
  RotateCw: HI.ReloadIcon as React.ElementType,
  Eye: HI.EyeIcon as React.ElementType,
  EyeOff: HI.ViewOffIcon as React.ElementType,
  LockKeyhole: HI.LockIcon as React.ElementType,
  Key: HI.Key01Icon as React.ElementType,
  User: HI.UserIcon as React.ElementType,
  UserPlus: HI.UserAdd01Icon as React.ElementType,
  UserMinus: HI.UserMinus01Icon as React.ElementType,
  UserCheck: HI.UserCheck01Icon as React.ElementType,
  Image: HI.Image01Icon as React.ElementType,
  Film: HI.Film01Icon as React.ElementType,
  Play: HI.PlayIcon as React.ElementType,
  Pause: HI.PauseIcon as React.ElementType,
  Square: HI.SquareIcon as React.ElementType,
  Mic: HI.Mic01Icon as React.ElementType,
  Headphones: HI.HeadphonesIcon as React.ElementType,
  Speaker: HI.SpeakerIcon as React.ElementType,
  Trash2: HI.Delete02Icon as React.ElementType,
  Archive: HI.Archive01Icon as React.ElementType,
  Filter: HI.FilterIcon as React.ElementType,
  List: HI.ListViewIcon as React.ElementType,
  Grid: HI.GridIcon as React.ElementType,
  BarChart: HI.BarChartIcon as React.ElementType,
  PieChart: HI.PieChartIcon as React.ElementType,
  LineChart: HI.ChartLineData01Icon as React.ElementType,
  TrendingUp: HI.ArrowUpRight01Icon as React.ElementType,
  Ghost: HI.GameboyIcon as React.ElementType,
  Gamepad2: HI.GameController01Icon as React.ElementType,
  Ambulance: HI.AmbulanceIcon as React.ElementType,
  Apple: HI.AppleIcon as React.ElementType,
  Waves: HI.WaveIcon as React.ElementType,
  Hand: HI.WavingHand01Icon as React.ElementType,
  Instagram: HI.InstagramIcon as React.ElementType,
  Facebook: HI.Facebook01Icon as React.ElementType,
  Twitter: HI.TwitterIcon as React.ElementType,
  Linkedin: HI.Linkedin01Icon as React.ElementType,
  Github: HI.GithubIcon as React.ElementType,
  Slack: HI.SlackIcon as React.ElementType,
  Discord: HI.DiscordIcon as React.ElementType,
  Youtube: HI.YoutubeIcon as React.ElementType,
  Spotify: HI.SpotifyIcon as React.ElementType,
  Pinterest: HI.PinterestIcon as React.ElementType,
  Twitch: HI.TwitchIcon as React.ElementType,
  Tiktok: HI.TiktokIcon as React.ElementType,
  Snapchat: HI.SnapchatIcon as React.ElementType,
  Whatsapp: HI.WhatsappIcon as React.ElementType,
  Telegram: HI.TelegramIcon as React.ElementType,
  Reddit: HI.RedditIcon as React.ElementType,
  Medium: HI.MediumIcon as React.ElementType,
  Behance: HI.Behance01Icon as React.ElementType,
  Dribbble: HI.DribbbleIcon as React.ElementType,
  Figma: HI.FigmaIcon as React.ElementType,
  Google: HI.GoogleIcon as React.ElementType,
  Microsoft: HI.MicrosoftIcon as React.ElementType,
  Amazon: HI.AmazonIcon as React.ElementType,
  Airbnb: HI.AirbnbIcon as React.ElementType,
  Uber: HI.UberIcon as React.ElementType,
  Brain: HI.Brain01Icon as React.ElementType,
  Rocket: HI.RocketIcon as React.ElementType,
  Code: HI.CodeIcon as React.ElementType,
  Bug: HI.Bug01Icon as React.ElementType,
  Dna: HI.DnaIcon as React.ElementType,
  Microscope: HI.MicroscopeIcon as React.ElementType,
  Telescope: HI.Telescope01Icon as React.ElementType,
  Compass: HI.Compass01Icon as React.ElementType,
  Flag: HI.Flag01Icon as React.ElementType,
  Stopwatch: HI.StopWatchIcon as React.ElementType,
  VideoOff: HI.VideoOffIcon as React.ElementType,
  VolumeHigh: HI.VolumeUpIcon as React.ElementType,
  VolumeLow: HI.VolumeMinusIcon as React.ElementType,
  VolumeMute: HI.VolumeMute01Icon as React.ElementType,
  Bluetooth: HI.BluetoothIcon as React.ElementType,
  Wifi: HI.Wifi01Icon as React.ElementType,
  Battery: HI.BatteryFullIcon as React.ElementType,
  BatteryCharging: HI.BatteryCharging01Icon as React.ElementType,
  Flashlight: HI.FlashlightIcon as React.ElementType,
  Scissors: HI.Scissor01Icon as React.ElementType,
  Paintbrush: HI.PaintBrush01Icon as React.ElementType,
  PenTool: HI.PenTool01Icon as React.ElementType,
  Eraser: HI.EraserIcon as React.ElementType,
  Ruler: HI.RulerIcon as React.ElementType,
  Magnet: HI.MagnetIcon as React.ElementType,
  Attachment: HI.Attachment01Icon as React.ElementType,
  Tag: HI.Tag01Icon as React.ElementType,
  Ticket: HI.Ticket01Icon as React.ElementType,
  Crown: HI.CrownIcon as React.ElementType,
  Diamond: HI.DiamondIcon as React.ElementType,
  Gem: HI.GemIcon as React.ElementType,
  IceCream: HI.IceCream01Icon as React.ElementType,
  Egg: HI.EggsIcon as React.ElementType,
  Motorbike: HI.Motorbike01Icon as React.ElementType,
  Hotel: HI.Hotel01Icon as React.ElementType,
  Mountain: HI.MountainIcon as React.ElementType,
  Beach: HI.BeachIcon as React.ElementType,
  Tree: HI.Tree01Icon as React.ElementType,
  Leaf: HI.Leaf01Icon as React.ElementType,
  Flower: HI.FlowerIcon as React.ElementType,
  Cactus: HI.CactusIcon as React.ElementType,
  AddCircle: HI.AddCircleIcon as React.ElementType,
  AddSquare: HI.AddSquareIcon as React.ElementType,
  AddTeam: HI.AddTeamIcon as React.ElementType,
  AddToList: HI.AddToListIcon as React.ElementType,
  AddressBook: HI.AddressBookIcon as React.ElementType,
  AiBrain: HI.AiBrain01Icon as React.ElementType,
  AiChat: HI.AiChat01Icon as React.ElementType,
  AiIdea: HI.AiIdeaIcon as React.ElementType,
  AiSearch: HI.AiSearchIcon as React.ElementType,
  AiSetting: HI.AiSettingIcon as React.ElementType,
  AlignBottom: HI.AlignBottomIcon as React.ElementType,
  AlignLeft: HI.AlignLeftIcon as React.ElementType,
  AlignRight: HI.AlignRightIcon as React.ElementType,
  AlignTop: HI.AlignTopIcon as React.ElementType,
  ArrowDownDouble: HI.ArrowDownDoubleIcon as React.ElementType,
  ArrowLeftDouble: HI.ArrowLeftDoubleIcon as React.ElementType,
  ArrowRightDouble: HI.ArrowRightDoubleIcon as React.ElementType,
  ArrowUpDouble: HI.ArrowUpDoubleIcon as React.ElementType,
  Backpack: HI.Backpack01Icon as React.ElementType,
  Bank: HI.BankIcon as React.ElementType,
  Bone: HI.Bone01Icon as React.ElementType,
  BookDownload: HI.BookDownloadIcon as React.ElementType,
  BookEdit: HI.BookEditIcon as React.ElementType,
  BookOpen: HI.BookOpen01Icon as React.ElementType,
  BookUpload: HI.BookUploadIcon as React.ElementType,
  BookmarkAdd: HI.BookmarkAdd01Icon as React.ElementType,
  BookmarkCheck: HI.BookmarkCheck01Icon as React.ElementType,
  BookmarkMinus: HI.BookmarkMinus01Icon as React.ElementType,
  BookmarkRemove: HI.BookmarkRemove01Icon as React.ElementType,
  Bread: HI.Bread01Icon as React.ElementType,
  Bridge: HI.BridgeIcon as React.ElementType,
  Building01: HI.Building01Icon as React.ElementType,
  Building02: HI.Building02Icon as React.ElementType,
  Building03: HI.Building03Icon as React.ElementType,
  Building04: HI.Building04Icon as React.ElementType,
  Building05: HI.Building05Icon as React.ElementType,
  Bus01: HI.Bus01Icon as React.ElementType,
  Bus02: HI.Bus02Icon as React.ElementType,
  Calculator: HI.CalculatorIcon as React.ElementType,
  CalendarAdd: HI.CalendarAdd01Icon as React.ElementType,
  CalendarBlock: HI.CalendarBlock01Icon as React.ElementType,
  CalendarRemove: HI.CalendarRemove01Icon as React.ElementType,
  CalendarSetting: HI.CalendarSetting01Icon as React.ElementType,
  CallAdd: HI.CallAddIcon as React.ElementType,
  CallInternal: HI.CallInternalIcon as React.ElementType,
  CallPaused: HI.CallPausedIcon as React.ElementType,
  CallReceived: HI.CallReceivedIcon as React.ElementType,
  CameraAdd: HI.CameraAdd01Icon as React.ElementType,
  CameraLens: HI.CameraLensIcon as React.ElementType,
  CancelCircle: HI.CancelCircleIcon as React.ElementType,
  Car: HI.Car01Icon as React.ElementType,
  ChatBot: HI.ChatBotIcon as React.ElementType,
  CheckList: HI.CheckListIcon as React.ElementType,
  CheckmarkBadge: HI.CheckmarkBadge01Icon as React.ElementType,
  CheckmarkCircle: HI.CheckmarkCircle01Icon as React.ElementType,
  Circle: HI.CircleIcon as React.ElementType,
  Clapping: HI.Clapping01Icon as React.ElementType,
  Clip: HI.ClipIcon as React.ElementType,
  CloudDownload: HI.CloudDownloadIcon as React.ElementType,
  CloudServer: HI.CloudServerIcon as React.ElementType,
  CloudUpload: HI.CloudUploadIcon as React.ElementType,
  CodeCircle: HI.CodeCircleIcon as React.ElementType,
  CodeFolder: HI.CodeFolderIcon as React.ElementType,
  ColorPicker: HI.ColorPickerIcon as React.ElementType,
  Command: HI.CommandIcon as React.ElementType,
  Comment: HI.Comment01Icon as React.ElementType,
  CommentAdd: HI.CommentAdd01Icon as React.ElementType,
  CommentBlock: HI.CommentBlock01Icon as React.ElementType,
  CommentRemove: HI.CommentRemove01Icon as React.ElementType,
  Computer: HI.ComputerIcon as React.ElementType,
  ComputerAdd: HI.ComputerAddIcon as React.ElementType,
  ComputerCheck: HI.ComputerCheckIcon as React.ElementType,
  ComputerCloud: HI.ComputerCloudIcon as React.ElementType,
  ComputerDesk: HI.ComputerDesk01Icon as React.ElementType,
  Connect: HI.ConnectIcon as React.ElementType,
  Cookie: HI.CookieIcon as React.ElementType,
  Copy01: HI.Copy01Icon as React.ElementType,
  Copy02: HI.Copy02Icon as React.ElementType,
  CreditCard: HI.CreditCardIcon as React.ElementType,
  CreditCardAccept: HI.CreditCardAcceptIcon as React.ElementType,
  CreditCardAdd: HI.CreditCardAddIcon as React.ElementType,
  CreditCardChange: HI.CreditCardChangeIcon as React.ElementType,
  CreditCardPos: HI.CreditCardPosIcon as React.ElementType,
  Crop: HI.CropIcon as React.ElementType,
  DashboardCircle: HI.DashboardCircleIcon as React.ElementType,
  DashboardSpeed: HI.DashboardSpeed01Icon as React.ElementType,
  DataRecovery: HI.DataRecoveryIcon as React.ElementType,
  Delete01: HI.Delete01Icon as React.ElementType,
  DeleteColumn: HI.DeleteColumnIcon as React.ElementType,
  DeleteRow: HI.DeleteRowIcon as React.ElementType,
  DeliveryTruck: HI.DeliveryTruck01Icon as React.ElementType,
  Desk01: HI.Desk01Icon as React.ElementType,
  Desk02: HI.Desk02Icon as React.ElementType,
  DirectionLeft: HI.DirectionLeft01Icon as React.ElementType,
  DirectionRight: HI.DirectionRight01Icon as React.ElementType,
  Discount01: HI.Discount01Icon as React.ElementType,
  Doc01: HI.Doc01Icon as React.ElementType,
  Dollar01: HI.Dollar01Icon as React.ElementType,
  Dollar02: HI.Dollar02Icon as React.ElementType,
  Download02: HI.Download02Icon as React.ElementType,
  DownloadCircle01: HI.DownloadCircle01Icon as React.ElementType,
  DownloadSquare01: HI.DownloadSquare01Icon as React.ElementType,
  Drag01: HI.Drag01Icon as React.ElementType,
  DragLeft01: HI.DragLeft01Icon as React.ElementType,
  DragRight01: HI.DragRight01Icon as React.ElementType,
  Energy: HI.EnergyIcon as React.ElementType,
  Engine: HI.EngineIcon as React.ElementType,
  FaceId: HI.FaceIdIcon as React.ElementType,
  FastWind: HI.FastWindIcon as React.ElementType,
  FileAdd: HI.FileAddIcon as React.ElementType,
  FileCloud: HI.FileCloudIcon as React.ElementType,
  FileDownload: HI.FileDownloadIcon as React.ElementType,
  FileEdit: HI.FileEditIcon as React.ElementType,
  FileEmpty01: HI.FileEmpty01Icon as React.ElementType,
  FileExport: HI.FileExportIcon as React.ElementType,
  FileImport: HI.FileImportIcon as React.ElementType,
  FileLocked: HI.FileLockedIcon as React.ElementType,
  FileMinus: HI.FileMinusIcon as React.ElementType,
  FileMusic: HI.FileMusicIcon as React.ElementType,
  FileRemove: HI.FileRemoveIcon as React.ElementType,
  FileSearch: HI.FileSearchIcon as React.ElementType,
  FileSecurity: HI.FileSecurityIcon as React.ElementType,
  FileStar: HI.FileStarIcon as React.ElementType,
  FileSync: HI.FileSyncIcon as React.ElementType,
  FileUnknown: HI.FileUnknownIcon as React.ElementType,
  FileUpload: HI.FileUploadIcon as React.ElementType,
  FileVideo: HI.FileVideoIcon as React.ElementType,
  FileZip: HI.FileZipIcon as React.ElementType,
  FilterAdd: HI.FilterAddIcon as React.ElementType,
  FilterEdit: HI.FilterEditIcon as React.ElementType,
  FilterHorizontal: HI.FilterHorizontalIcon as React.ElementType,
  FilterRemove: HI.FilterRemoveIcon as React.ElementType,
  FilterVertical: HI.FilterVerticalIcon as React.ElementType,
  Fire02: HI.Fire02Icon as React.ElementType,
  FirePit: HI.FirePitIcon as React.ElementType,
  Flag02: HI.Flag02Icon as React.ElementType,
  Flag03: HI.Flag03Icon as React.ElementType,
  Flash: HI.FlashIcon as React.ElementType,
  FlashOff: HI.FlashOffIcon as React.ElementType,
  FlowerPot: HI.FlowerPotIcon as React.ElementType,
  FocusPoint: HI.FocusPointIcon as React.ElementType,
  FolderDownload: HI.FolderDownloadIcon as React.ElementType,
  FolderEdit: HI.FolderEditIcon as React.ElementType,
  FolderMinus: HI.FolderMinusIcon as React.ElementType,
  FolderMusic: HI.FolderMusicIcon as React.ElementType,
  FolderOff: HI.FolderOffIcon as React.ElementType,
  FolderOpen: HI.FolderOpenIcon as React.ElementType,
  FolderPin: HI.FolderPinIcon as React.ElementType,
  FolderRemove: HI.FolderRemoveIcon as React.ElementType,
  FolderSearch: HI.FolderSearchIcon as React.ElementType,
  FolderUpload: HI.FolderUploadIcon as React.ElementType,
  FolderVideo: HI.FolderVideoIcon as React.ElementType,
  FolderView: HI.FolderViewIcon as React.ElementType,
  FolderZip: HI.FolderZipIcon as React.ElementType,
  Forward01: HI.Forward01Icon as React.ElementType,
  FuelStation: HI.FuelStationIcon as React.ElementType,
  FullScreen: HI.FullScreenIcon as React.ElementType,
  Garage: HI.GarageIcon as React.ElementType,
  Gif01: HI.Gif01Icon as React.ElementType,
  Gift: HI.GiftIcon as React.ElementType,
  Glasses: HI.GlassesIcon as React.ElementType,
  Globe02: HI.Globe02Icon as React.ElementType,
  Gps01: HI.Gps01Icon as React.ElementType,
  GpsDisconnected: HI.GpsDisconnectedIcon as React.ElementType,
  GpsOff01: HI.GpsOff01Icon as React.ElementType,
  GpsSignal01: HI.GpsSignal01Icon as React.ElementType,
  HandGrip: HI.HandGripIcon as React.ElementType,
  HandPointingLeft01: HI.HandPointingLeft01Icon as React.ElementType,
  HandPointingRight01: HI.HandPointingRight01Icon as React.ElementType,
  Hanger: HI.HangerIcon as React.ElementType,
  Hat: HI.HatIcon as React.ElementType,
  Happy01: HI.Happy01Icon as React.ElementType,
  Heading01: HI.Heading01Icon as React.ElementType,
  HeadphoneMute: HI.HeadphoneMuteIcon as React.ElementType,
  Health: HI.HealthIcon as React.ElementType,
  Hexagon01: HI.Hexagon01Icon as React.ElementType,
  Home02: HI.Home02Icon as React.ElementType,
  Home03: HI.Home03Icon as React.ElementType,
  Home04: HI.Home04Icon as React.ElementType,
  Hospital01: HI.Hospital01Icon as React.ElementType,
  HospitalBed01: HI.HospitalBed01Icon as React.ElementType,
  HospitalLocation: HI.HospitalLocationIcon as React.ElementType,
  HotAirBalloon: HI.HotAirBalloonIcon as React.ElementType,
  Hotel02: HI.Hotel02Icon as React.ElementType,
  Hourglass: HI.HourglassIcon as React.ElementType,
  HourglassOff: HI.HourglassOffIcon as React.ElementType,
  House01: HI.House01Icon as React.ElementType,
  House02: HI.House02Icon as React.ElementType,
  House03: HI.House03Icon as React.ElementType,
  House04: HI.House04Icon as React.ElementType,
  House05: HI.House05Icon as React.ElementType,
  Idea01: HI.Idea01Icon as React.ElementType,
  ImageAdd01: HI.ImageAdd01Icon as React.ElementType,
  ImageDelete01: HI.ImageDelete01Icon as React.ElementType,
  ImageDone01: HI.ImageDone01Icon as React.ElementType,
  ImageDownload02: HI.ImageDownload02Icon as React.ElementType,
  ImageFlipHorizontal: HI.ImageFlipHorizontalIcon as React.ElementType,
  ImageFlipVertical: HI.ImageFlipVerticalIcon as React.ElementType,
  ImageNotFound01: HI.ImageNotFound01Icon as React.ElementType,
  ImageRemove01: HI.ImageRemove01Icon as React.ElementType,
  ImageUpload01: HI.ImageUpload01Icon as React.ElementType,
  Injection: HI.InjectionIcon as React.ElementType,
  Invoice01: HI.Invoice01Icon as React.ElementType,
  Judge: HI.JudgeIcon as React.ElementType,
  Key02: HI.Key02Icon as React.ElementType,
  Knowledge01: HI.Knowledge01Icon as React.ElementType,
  Label: HI.LabelIcon as React.ElementType,
  LabelImportant: HI.LabelImportantIcon as React.ElementType,
  LanguageCircle: HI.LanguageCircleIcon as React.ElementType,
  LanguageSkill: HI.LanguageSkillIcon as React.ElementType,
  LanguageSquare: HI.LanguageSquareIcon as React.ElementType,
  LaptopAdd: HI.LaptopAddIcon as React.ElementType,
  LaptopCharging: HI.LaptopChargingIcon as React.ElementType,
  LaptopCheck: HI.LaptopCheckIcon as React.ElementType,
  LaptopCloud: HI.LaptopCloudIcon as React.ElementType,
  LaptopIssue: HI.LaptopIssueIcon as React.ElementType,
  LaptopPerformance: HI.LaptopPerformanceIcon as React.ElementType,
  LaptopPhoneSync: HI.LaptopPhoneSyncIcon as React.ElementType,
  LaptopProgramming: HI.LaptopProgrammingIcon as React.ElementType,
  LaptopRemove: HI.LaptopRemoveIcon as React.ElementType,
  LaptopSettings: HI.LaptopSettingsIcon as React.ElementType,
  LaptopVideo: HI.LaptopVideoIcon as React.ElementType,
  LassoTool01: HI.LassoTool01Icon as React.ElementType,
  Laughing: HI.LaughingIcon as React.ElementType,
  LayerAdd: HI.LayerAddIcon as React.ElementType,
  LayerMask01: HI.LayerMask01Icon as React.ElementType,
  Layers02: HI.Layers02Icon as React.ElementType,
  LayersLogo: HI.LayersLogoIcon as React.ElementType,
  Layout01: HI.Layout01Icon as React.ElementType,
  Leaf02: HI.Leaf02Icon as React.ElementType,
  Leaf03: HI.Leaf03Icon as React.ElementType,
  LetterSpacing: HI.LetterSpacingIcon as React.ElementType,
  Line: HI.LineIcon as React.ElementType,
  Loading01: HI.Loading01Icon as React.ElementType,
  Loading02: HI.Loading02Icon as React.ElementType,
  Location01: HI.Location01Icon as React.ElementType,
  LocationAdd01: HI.LocationAdd01Icon as React.ElementType,
  LocationCheck01: HI.LocationCheck01Icon as React.ElementType,
  LocationOffline01: HI.LocationOffline01Icon as React.ElementType,
  LocationRemove01: HI.LocationRemove01Icon as React.ElementType,
  LocationShare01: HI.LocationShare01Icon as React.ElementType,
  LocationStar01: HI.LocationStar01Icon as React.ElementType,
  LocationUpdate01: HI.LocationUpdate01Icon as React.ElementType,
  LockKey: HI.LockKeyIcon as React.ElementType,
  LockPassword: HI.LockPasswordIcon as React.ElementType,
  LoginCircle01: HI.LoginCircle01Icon as React.ElementType,
  LoginSquare01: HI.LoginSquare01Icon as React.ElementType,
  LogoutCircle01: HI.LogoutCircle01Icon as React.ElementType,
  LogoutSquare01: HI.LogoutSquare01Icon as React.ElementType,
  Magnet01: HI.Magnet01Icon as React.ElementType,
  Magnet02: HI.Magnet02Icon as React.ElementType,
  MailDownload01: HI.MailDownload01Icon as React.ElementType,
  MailEdit01: HI.MailEdit01Icon as React.ElementType,
  MailReceive01: HI.MailReceive01Icon as React.ElementType,
  MailSearch01: HI.MailSearch01Icon as React.ElementType,
  MailSend01: HI.MailSend01Icon as React.ElementType,
  MailUpload01: HI.MailUpload01Icon as React.ElementType,
  MapPin: HI.MapPinIcon as React.ElementType,
  MapPinpoint01: HI.MapPinpoint01Icon as React.ElementType,
  Math: HI.MathIcon as React.ElementType,
  Maximize02: HI.Maximize02Icon as React.ElementType,
  MaximizeScreen: HI.MaximizeScreenIcon as React.ElementType,
  Medal02: HI.Medal02Icon as React.ElementType,
  MedalFirstPlace: HI.MedalFirstPlaceIcon as React.ElementType,
  MedalSecondPlace: HI.MedalSecondPlaceIcon as React.ElementType,
  MedalThirdPlace: HI.MedalThirdPlaceIcon as React.ElementType,
  MedicalFile: HI.MedicalFileIcon as React.ElementType,
  MedicalMask: HI.MedicalMaskIcon as React.ElementType,
  MeetingRoom: HI.MeetingRoomIcon as React.ElementType,
  Megaphone01: HI.Megaphone01Icon as React.ElementType,
  Menu01: HI.Menu01Icon as React.ElementType,
  MenuCircle: HI.MenuCircleIcon as React.ElementType,
  MenuCollapse: HI.MenuCollapseIcon as React.ElementType,
  MenuSquare: HI.MenuSquareIcon as React.ElementType,
  MenuTwoLine: HI.MenuTwoLineIcon as React.ElementType,
  Message01: HI.Message01Icon as React.ElementType,
  MessageAdd01: HI.MessageAdd01Icon as React.ElementType,
  MessageBlocked: HI.MessageBlockedIcon as React.ElementType,
  MessageCancel01: HI.MessageCancel01Icon as React.ElementType,
  MessageDone01: HI.MessageDone01Icon as React.ElementType,
  MessageDownload01: HI.MessageDownload01Icon as React.ElementType,
  MessageEdit01: HI.MessageEdit01Icon as React.ElementType,
  MessageFavourite01: HI.MessageFavourite01Icon as React.ElementType,
  MessageLock01: HI.MessageLock01Icon as React.ElementType,
  MessageMultiple01: HI.MessageMultiple01Icon as React.ElementType,
  MessageNotification01: HI.MessageNotification01Icon as React.ElementType,
  MessagePreview01: HI.MessagePreview01Icon as React.ElementType,
  MessageProgramming: HI.MessageProgrammingIcon as React.ElementType,
  MessageQuestion: HI.MessageQuestionIcon as React.ElementType,
  MessageSearch01: HI.MessageSearch01Icon as React.ElementType,
  MessageTranslate: HI.MessageTranslateIcon as React.ElementType,
  MessageUnlock01: HI.MessageUnlock01Icon as React.ElementType,
  MessageUpload01: HI.MessageUpload01Icon as React.ElementType,
  MessageUser01: HI.MessageUser01Icon as React.ElementType,
  Minimize02: HI.Minimize02Icon as React.ElementType,
  MinimizeScreen: HI.MinimizeScreenIcon as React.ElementType,
  Mirror: HI.MirrorIcon as React.ElementType,
  MirroringScreen: HI.MirroringScreenIcon as React.ElementType,
  Moon01: HI.Moon01Icon as React.ElementType,
  MoonEclipse: HI.MoonEclipseIcon as React.ElementType,
  MoonFastWind: HI.MoonFastWindIcon as React.ElementType,
  MoonLanding: HI.MoonLandingIcon as React.ElementType,
  MoreHorizontal: HI.MoreHorizontalIcon as React.ElementType,
  MoreVertical: HI.MoreVerticalIcon as React.ElementType,
  Note01: HI.Note01Icon as React.ElementType,
  Note02: HI.Note02Icon as React.ElementType,
  NoteAdd: HI.NoteAddIcon as React.ElementType,
  NoteDone: HI.NoteDoneIcon as React.ElementType,
  NoteEdit: HI.NoteEditIcon as React.ElementType,
  NoteRemove: HI.NoteRemoveIcon as React.ElementType,
  Notebook01: HI.Notebook01Icon as React.ElementType,
  Notebook02: HI.Notebook02Icon as React.ElementType,
  Notification02: HI.Notification02Icon as React.ElementType,
  NotificationBlock01: HI.NotificationBlock01Icon as React.ElementType,
  NotificationCircle: HI.NotificationCircleIcon as React.ElementType,
  NotificationOff01: HI.NotificationOff01Icon as React.ElementType,
  NotificationSnooze01: HI.NotificationSnooze01Icon as React.ElementType,
  NotificationSquare: HI.NotificationSquareIcon as React.ElementType,
  Office: HI.OfficeIcon as React.ElementType,
  Office365: HI.Office365Icon as React.ElementType,
  OfficeChair: HI.OfficeChairIcon as React.ElementType,
  OilBarrel: HI.OilBarrelIcon as React.ElementType,
  OnlineLearning01: HI.OnlineLearning01Icon as React.ElementType,
  OpenCaption: HI.OpenCaptionIcon as React.ElementType,
  Option: HI.OptionIcon as React.ElementType,
  Orange: HI.OrangeIcon as React.ElementType,
  Package01: HI.Package01Icon as React.ElementType,
  PackageAdd01: HI.PackageAdd01Icon as React.ElementType,
  PackageOpen: HI.PackageOpenIcon as React.ElementType,
  PackageRemove01: HI.PackageRemove01Icon as React.ElementType,
  PackageSearch01: HI.PackageSearch01Icon as React.ElementType,
  PackageSent01: HI.PackageSent01Icon as React.ElementType,
  PaintBoard: HI.PaintBoardIcon as React.ElementType,
  PaintBucket: HI.PaintBucketIcon as React.ElementType,
  Pan01: HI.Pan01Icon as React.ElementType,
  Paragraph: HI.ParagraphIcon as React.ElementType,
  ParagraphBulletsPoint01: HI.ParagraphBulletsPoint01Icon as React.ElementType,
  ParagraphSpacing: HI.ParagraphSpacingIcon as React.ElementType,
  Passport01: HI.Passport01Icon as React.ElementType,
  PasswordValidation: HI.PasswordValidationIcon as React.ElementType,
  Path: HI.PathIcon as React.ElementType,
  PauseCircle: HI.PauseCircleIcon as React.ElementType,
  Pdf01: HI.Pdf01Icon as React.ElementType,
  Pen01: HI.Pen01Icon as React.ElementType,
  PenToolAdd: HI.PenToolAddIcon as React.ElementType,
  PenToolMinus: HI.PenToolMinusIcon as React.ElementType,
  Pentagon01: HI.Pentagon01Icon as React.ElementType,
  Percent: HI.PercentIcon as React.ElementType,
  PercentCircle: HI.PercentCircleIcon as React.ElementType,
  PercentSquare: HI.PercentSquareIcon as React.ElementType,
  PhoneCheck: HI.PhoneCheckIcon as React.ElementType,
  PhoneOff01: HI.PhoneOff01Icon as React.ElementType,
  PlayCircle: HI.PlayCircleIcon as React.ElementType,
  PlayList: HI.PlayListIcon as React.ElementType,
  PlayListAdd: HI.PlayListAddIcon as React.ElementType,
  PlayListFavourite01: HI.PlayListFavourite01Icon as React.ElementType,
  PlayListMinus: HI.PlayListMinusIcon as React.ElementType,
  PlayListRemove: HI.PlayListRemoveIcon as React.ElementType,
  PlaySquare: HI.PlaySquareIcon as React.ElementType,
  Plug02: HI.Plug02Icon as React.ElementType,
  PlugSocket: HI.PlugSocketIcon as React.ElementType,
  Podcast: HI.PodcastIcon as React.ElementType,
  Polygon: HI.PolygonIcon as React.ElementType,
  Presentation01: HI.Presentation01Icon as React.ElementType,
  PresentationBarChart01: HI.PresentationBarChart01Icon as React.ElementType,
  PresentationLineChart01: HI.PresentationLineChart01Icon as React.ElementType,
  PresentationOnline: HI.PresentationOnlineIcon as React.ElementType,
  PresentationPodium: HI.PresentationPodiumIcon as React.ElementType,
  Printer: HI.PrinterIcon as React.ElementType,
  PrinterOff: HI.PrinterOffIcon as React.ElementType,
  ProductLoading: HI.ProductLoadingIcon as React.ElementType,
  ProgrammingFlag: HI.ProgrammingFlagIcon as React.ElementType,
  Projector01: HI.Projector01Icon as React.ElementType,
  PropertyAdd: HI.PropertyAddIcon as React.ElementType,
  PropertyDelete: HI.PropertyDeleteIcon as React.ElementType,
  PropertyEdit: HI.PropertyEditIcon as React.ElementType,
  PropertySearch: HI.PropertySearchIcon as React.ElementType,
  PropertyView: HI.PropertyViewIcon as React.ElementType,
  Pulse01: HI.Pulse01Icon as React.ElementType,
  PulseRectangle01: HI.PulseRectangle01Icon as React.ElementType,
  Puzzle: HI.PuzzleIcon as React.ElementType,
  QrCode01: HI.QrCode01Icon as React.ElementType,
  Question: HI.QuestionIcon as React.ElementType,
  QuoteDown: HI.QuoteDownIcon as React.ElementType,
  QuoteDownCircle: HI.QuoteDownCircleIcon as React.ElementType,
  QuoteDownSquare: HI.QuoteDownSquareIcon as React.ElementType,
  QuoteUp: HI.QuoteUpIcon as React.ElementType,
  QuoteUpCircle: HI.QuoteUpCircleIcon as React.ElementType,
  QuoteUpSquare: HI.QuoteUpSquareIcon as React.ElementType,
  Quotes: HI.QuotesIcon as React.ElementType,
  Radar01: HI.Radar01Icon as React.ElementType,
  Rainbow: HI.RainbowIcon as React.ElementType,
  ReceiptDollar: HI.ReceiptDollarIcon as React.ElementType,
  Redo02: HI.Redo02Icon as React.ElementType,
  Refresh03: HI.Refresh03Icon as React.ElementType,
  RefreshDot: HI.RefreshDotIcon as React.ElementType,
  RemoveCircle: HI.RemoveCircleIcon as React.ElementType,
  RemoveFemale: HI.RemoveFemaleIcon as React.ElementType,
  RemoveMale: HI.RemoveMaleIcon as React.ElementType,
  RemoveSquare: HI.RemoveSquareIcon as React.ElementType,
  Repeat: HI.RepeatIcon as React.ElementType,
  RepeatOff: HI.RepeatOffIcon as React.ElementType,
  Replay: HI.ReplayIcon as React.ElementType,
  Restaurant02: HI.Restaurant02Icon as React.ElementType,
  RestaurantTable: HI.RestaurantTableIcon as React.ElementType,
  Rocket01: HI.Rocket01Icon as React.ElementType,
  Rocket02: HI.Rocket02Icon as React.ElementType,
  RotateBottomLeft: HI.RotateBottomLeftIcon as React.ElementType,
  RotateBottomRight: HI.RotateBottomRightIcon as React.ElementType,
  RotateLeft01: HI.RotateLeft01Icon as React.ElementType,
  RotateRight01: HI.RotateRight01Icon as React.ElementType,
  RotateTopLeft: HI.RotateTopLeftIcon as React.ElementType,
  RotateTopRight: HI.RotateTopRightIcon as React.ElementType,
  Route01: HI.Route01Icon as React.ElementType,
  RouteBlock: HI.RouteBlockIcon as React.ElementType,
  Router01: HI.Router01Icon as React.ElementType,
  RowDelete: HI.RowDeleteIcon as React.ElementType,
  RowInsert: HI.RowInsertIcon as React.ElementType,
  Rss01: HI.RssIcon as React.ElementType,
  RssError: HI.RssErrorIcon as React.ElementType,
  RunningShoes: HI.RunningShoesIcon as React.ElementType,
  Sad01: HI.Sad01Icon as React.ElementType,
  SadDizzy: HI.SadDizzyIcon as React.ElementType,
  Safe: HI.SafeIcon as React.ElementType,
  SafeDelivery01: HI.SafeDelivery01Icon as React.ElementType,
  SaleTag01: HI.SaleTag01Icon as React.ElementType,
  Sandals: HI.SandalsIcon as React.ElementType,
  Savings: HI.SavingsIcon as React.ElementType,
  Scan: HI.ScanIcon as React.ElementType,
  School01: HI.School01Icon as React.ElementType,
  SchoolBell01: HI.SchoolBell01Icon as React.ElementType,
  SchoolBus: HI.SchoolBusIcon as React.ElementType,
  SchoolTie: HI.SchoolTieIcon as React.ElementType,
  ScreenRotation: HI.ScreenRotationIcon as React.ElementType,
  SearchAdd: HI.SearchAddIcon as React.ElementType,
  SearchCircle: HI.SearchCircleIcon as React.ElementType,
  SearchDollar: HI.SearchDollarIcon as React.ElementType,
  SearchList01: HI.SearchList01Icon as React.ElementType,
  SearchMinus: HI.SearchMinusIcon as React.ElementType,
  SearchRemove: HI.SearchRemoveIcon as React.ElementType,
  SearchReplace: HI.SearchReplaceIcon as React.ElementType,
  SearchSquare: HI.SearchSquareIcon as React.ElementType,
  Security: HI.SecurityIcon as React.ElementType,
  SecurityBlock: HI.SecurityBlockIcon as React.ElementType,
  SecurityCheck: HI.SecurityCheckIcon as React.ElementType,
  SecurityLock: HI.SecurityLockIcon as React.ElementType,
  SecurityValidation: HI.SecurityValidationIcon as React.ElementType,
  SecurityWifi: HI.SecurityWifiIcon as React.ElementType,
  ServerStack01: HI.ServerStack01Icon as React.ElementType,
  SettingDone01: HI.SettingDone01Icon as React.ElementType,
  SettingError03: HI.SettingError03Icon as React.ElementType,
  Shapes: HI.ShapesIcon as React.ElementType,
  Share02: HI.Share02Icon as React.ElementType,
  ShareKnowledge: HI.ShareKnowledgeIcon as React.ElementType,
  ShareLocation01: HI.ShareLocation01Icon as React.ElementType,
  Shield02: HI.Shield02Icon as React.ElementType,
  ShieldEnergy: HI.ShieldEnergyIcon as React.ElementType,
  ShieldKey: HI.ShieldKeyIcon as React.ElementType,
  ShieldUser: HI.ShieldUserIcon as React.ElementType,
  ShipmentTracking: HI.ShipmentTrackingIcon as React.ElementType,
  Shirt01: HI.Shirt01Icon as React.ElementType,
  ShuffleSquare: HI.ShuffleSquareIcon as React.ElementType,
  SidebarBottom: HI.SidebarBottomIcon as React.ElementType,
  SidebarLeft01: HI.SidebarLeft01Icon as React.ElementType,
  SidebarRight01: HI.SidebarRight01Icon as React.ElementType,
  SidebarTop: HI.SidebarTopIcon as React.ElementType,
  SlidersHorizontal: HI.SlidersHorizontalIcon as React.ElementType,
  SlidersVertical: HI.SlidersVerticalIcon as React.ElementType,
  SmartAc: HI.SmartAcIcon as React.ElementType,
  SmartPhone02: HI.SmartPhone02Icon as React.ElementType,
  SmartPhoneLandscape: HI.SmartPhoneLandscapeIcon as React.ElementType,
  SmartWatch01: HI.SmartWatch01Icon as React.ElementType,
  SmileDizzy: HI.SmileDizzyIcon as React.ElementType,
  Snow: HI.SnowIcon as React.ElementType,
  SolarEnergy: HI.SolarEnergyIcon as React.ElementType,
  SolarPanel01: HI.SolarPanel01Icon as React.ElementType,
  SortByDown01: HI.SortByDown01Icon as React.ElementType,
  SortByUp01: HI.SortByUp01Icon as React.ElementType,
  SortingDown: HI.SortingDownIcon as React.ElementType,
  SortingUp: HI.SortingUpIcon as React.ElementType,
  SpeechToText: HI.SpeechToTextIcon as React.ElementType,
  Spirals: HI.SpiralsIcon as React.ElementType,
  Split: HI.SplitIcon as React.ElementType,
  SquareArrowDown01: HI.SquareArrowDown01Icon as React.ElementType,
  SquareArrowDownDouble: HI.SquareArrowDownDoubleIcon as React.ElementType,
  SquareArrowDownLeft: HI.SquareArrowDownLeftIcon as React.ElementType,
  SquareArrowDownRight: HI.SquareArrowDownRightIcon as React.ElementType,
  SquareArrowExpand01: HI.SquareArrowExpand01Icon as React.ElementType,
  SquareArrowLeft01: HI.SquareArrowLeft01Icon as React.ElementType,
  SquareArrowLeftDouble: HI.SquareArrowLeftDoubleIcon as React.ElementType,
  SquareArrowLeftRight: HI.SquareArrowLeftRightIcon as React.ElementType,
  SquareArrowReload01: HI.SquareArrowReload01Icon as React.ElementType,
  SquareArrowRight01: HI.SquareArrowRight01Icon as React.ElementType,
  SquareArrowRightDouble: HI.SquareArrowRightDoubleIcon as React.ElementType,
  SquareArrowShrink01: HI.SquareArrowShrink01Icon as React.ElementType,
  SquareArrowUp01: HI.SquareArrowUp01Icon as React.ElementType,
  SquareArrowUpDouble: HI.SquareArrowUpDoubleIcon as React.ElementType,
  SquareArrowUpDown: HI.SquareArrowUpDownIcon as React.ElementType,
  SquareArrowUpLeft: HI.SquareArrowUpLeftIcon as React.ElementType,
  SquareLock01: HI.SquareLock01Icon as React.ElementType,
  SquareLockPassword: HI.SquareLockPasswordIcon as React.ElementType,
  SquareUnlock01: HI.SquareUnlock01Icon as React.ElementType,
  StarCircle: HI.StarCircleIcon as React.ElementType,
  StarFace: HI.StarFaceIcon as React.ElementType,
  StarOff: HI.StarOffIcon as React.ElementType,
  Stethoscope02: HI.Stethoscope02Icon as React.ElementType,
  Stop: HI.StopIcon as React.ElementType,
  StopCircle: HI.StopCircleIcon as React.ElementType,
  Store01: HI.Store01Icon as React.ElementType,
  StoreAdd01: HI.StoreAdd01Icon as React.ElementType,
  StoreLocation01: HI.StoreLocation01Icon as React.ElementType,
  StoreRemove01: HI.StoreRemove01Icon as React.ElementType,
  StoreVerified01: HI.StoreVerified01Icon as React.ElementType,
  Structure01: HI.Structure01Icon as React.ElementType,
  StructureFolder: HI.StructureFolderIcon as React.ElementType,
  Student: HI.StudentIcon as React.ElementType,
  StudentCard: HI.StudentCardIcon as React.ElementType,
  Subtitle: HI.SubtitleIcon as React.ElementType,
  Sun02: HI.Sun02Icon as React.ElementType,
  SunCloud01: HI.SunCloud01Icon as React.ElementType,
  SunCloudAngledRain01: HI.SunCloudAngledRain01Icon as React.ElementType,
  SunCloudBigRain01: HI.SunCloudBigRain01Icon as React.ElementType,
  SunCloudFastWind01: HI.SunCloudFastWind01Icon as React.ElementType,
  SunCloudHailstone01: HI.SunCloudHailstone01Icon as React.ElementType,
  SunCloudLittleRain01: HI.SunCloudLittleRain01Icon as React.ElementType,
  SunCloudLittleSnow01: HI.SunCloudLittleSnow01Icon as React.ElementType,
  SunCloudMidRain01: HI.SunCloudMidRain01Icon as React.ElementType,
  SunCloudMidSnow01: HI.SunCloudMidSnow01Icon as React.ElementType,
  SunCloudSlowWind01: HI.SunCloudSlowWind01Icon as React.ElementType,
  SunCloudSnow01: HI.SunCloudSnow01Icon as React.ElementType,
  Sunglasses: HI.SunglassesIcon as React.ElementType,
  Sunrise: HI.SunriseIcon as React.ElementType,
  Sunset: HI.SunsetIcon as React.ElementType,
  Swimming: HI.SwimmingIcon as React.ElementType,
  SwimmingCap: HI.SwimmingCapIcon as React.ElementType,
  Table01: HI.Table01Icon as React.ElementType,
  TableLamp01: HI.TableLamp01Icon as React.ElementType,
  TableRound: HI.TableRoundIcon as React.ElementType,
  Tablet02: HI.Tablet02Icon as React.ElementType,
  TabletPen: HI.TabletPenIcon as React.ElementType,
  Tags: HI.TagsIcon as React.ElementType,
  Target02: HI.Target02Icon as React.ElementType,
  TargetDollar: HI.TargetDollarIcon as React.ElementType,
  TelevisionTable: HI.TelevisionTableIcon as React.ElementType,
  Temperature: HI.TemperatureIcon as React.ElementType,
  TennisBall: HI.TennisBallIcon as React.ElementType,
  Text: HI.TextIcon as React.ElementType,
  TextAlignCenter: HI.TextAlignCenterIcon as React.ElementType,
  TextAlignJustifyCenter: HI.TextAlignJustifyCenterIcon as React.ElementType,
  TextAlignJustifyLeft: HI.TextAlignJustifyLeftIcon as React.ElementType,
  TextAlignJustifyRight: HI.TextAlignJustifyRightIcon as React.ElementType,
  TextAlignLeft01: HI.TextAlignLeft01Icon as React.ElementType,
  TextAlignRight01: HI.TextAlignRight01Icon as React.ElementType,
  TextBold: HI.TextBoldIcon as React.ElementType,
  TextCircle: HI.TextCircleIcon as React.ElementType,
  TextColor: HI.TextColorIcon as React.ElementType,
  TextCreation: HI.TextCreationIcon as React.ElementType,
  TextFont: HI.TextFontIcon as React.ElementType,
  TextIndent01: HI.TextIndent01Icon as React.ElementType,
  TextIndentLess: HI.TextIndentLessIcon as React.ElementType,
  TextIndentMore: HI.TextIndentMoreIcon as React.ElementType,
  TextItalic: HI.TextItalicIcon as React.ElementType,
  TextItalicSlash: HI.TextItalicSlashIcon as React.ElementType,
  TextKerning: HI.TextKerningIcon as React.ElementType,
  TextSelection: HI.TextSelectionIcon as React.ElementType,
  TextSquare: HI.TextSquareIcon as React.ElementType,
  TextStrikethrough: HI.TextStrikethroughIcon as React.ElementType,
  TextSubscript: HI.TextSubscriptIcon as React.ElementType,
  TextSuperscript: HI.TextSuperscriptIcon as React.ElementType,
  TextTracking: HI.TextTrackingIcon as React.ElementType,
  TextUnderline: HI.TextUnderlineIcon as React.ElementType,
  TextWrap: HI.TextWrapIcon as React.ElementType,
  Thermometer: HI.ThermometerIcon as React.ElementType,
  ThermometerCold: HI.ThermometerColdIcon as React.ElementType,
  ThermometerWarm: HI.ThermometerWarmIcon as React.ElementType,
  ThumbsDown: HI.ThumbsDownIcon as React.ElementType,
  ThumbsUp: HI.ThumbsUpIcon as React.ElementType,
  TicketStar: HI.TicketStarIcon as React.ElementType,
  Time01: HI.Time01Icon as React.ElementType,
  TimeHalfPass: HI.TimeHalfPassIcon as React.ElementType,
  TimeManagement: HI.TimeManagementIcon as React.ElementType,
  TimeManagementCircle: HI.TimeManagementCircleIcon as React.ElementType,
  TimeQuarter02: HI.TimeQuarter02Icon as React.ElementType,
  TimeQuarterPass: HI.TimeQuarterPassIcon as React.ElementType,
  TimeSchedule: HI.TimeScheduleIcon as React.ElementType,
  TimeSetting01: HI.TimeSetting01Icon as React.ElementType,
  TimeZone: HI.TimeZoneIcon as React.ElementType,
  Timeline: HI.TimelineIcon as React.ElementType,
  TimelineEvent: HI.TimelineEventIcon as React.ElementType,
  TimelineList: HI.TimelineListIcon as React.ElementType,
  Timer01: HI.Timer01Icon as React.ElementType,
  Timer02: HI.Timer02Icon as React.ElementType,
  ToggleOff: HI.ToggleOffIcon as React.ElementType,
  ToggleOn: HI.ToggleOnIcon as React.ElementType,
  Tools: HI.ToolsIcon as React.ElementType,
  Touch01: HI.Touch01Icon as React.ElementType,
  TouchInteraction01: HI.TouchInteraction01Icon as React.ElementType,
  TouchLocked01: HI.TouchLocked01Icon as React.ElementType,
  Touchpad01: HI.Touchpad01Icon as React.ElementType,
  TrafficLight: HI.TrafficLightIcon as React.ElementType,
  Train01: HI.Train01Icon as React.ElementType,
  Trampoline: HI.TrampolineIcon as React.ElementType,
  Transaction: HI.TransactionIcon as React.ElementType,
  TransactionHistory: HI.TransactionHistoryIcon as React.ElementType,
  Translate: HI.TranslateIcon as React.ElementType,
  Translation: HI.TranslationIcon as React.ElementType,
  Tree02: HI.Tree02Icon as React.ElementType,
  Tree03: HI.Tree03Icon as React.ElementType,
  Tree04: HI.Tree04Icon as React.ElementType,
  Tree05: HI.Tree05Icon as React.ElementType,
  Tree06: HI.Tree06Icon as React.ElementType,
  Tree07: HI.Tree07Icon as React.ElementType,
  Triangle01: HI.Triangle01Icon as React.ElementType,
  Triangle02: HI.Triangle02Icon as React.ElementType,
  Triangle03: HI.Triangle03Icon as React.ElementType,
  Truck: HI.TruckIcon as React.ElementType,
  TruckDelivery: HI.TruckDeliveryIcon as React.ElementType,
  TruckReturn: HI.TruckReturnIcon as React.ElementType,
  Txt01: HI.Txt01Icon as React.ElementType,
  Umbrella: HI.UmbrellaIcon as React.ElementType,
  UmbrellaDollar: HI.UmbrellaDollarIcon as React.ElementType,
  Undo02: HI.Undo02Icon as React.ElementType,
  UnfoldLess: HI.UnfoldLessIcon as React.ElementType,
  UnfoldMore: HI.UnfoldMoreIcon as React.ElementType,
  Unhappy: HI.UnhappyIcon as React.ElementType,
  Unlink01: HI.Unlink01Icon as React.ElementType,
  Upload02: HI.Upload02Icon as React.ElementType,
  UploadCircle01: HI.UploadCircle01Icon as React.ElementType,
  UploadSquare01: HI.UploadSquare01Icon as React.ElementType,
  Usb: HI.UsbIcon as React.ElementType,
  UsbBugs: HI.UsbBugsIcon as React.ElementType,
  UsbMemory01: HI.UsbMemory01Icon as React.ElementType,
  UsbNotConnected01: HI.UsbNotConnected01Icon as React.ElementType,
  UserAccount: HI.UserAccountIcon as React.ElementType,
  UserBlock01: HI.UserBlock01Icon as React.ElementType,
  UserCircle02: HI.UserCircle02Icon as React.ElementType,
  UserEdit01: HI.UserEdit01Icon as React.ElementType,
  UserIdVerification: HI.UserIdVerificationIcon as React.ElementType,
  UserList: HI.UserListIcon as React.ElementType,
  UserLock01: HI.UserLock01Icon as React.ElementType,
  UserLove01: HI.UserLove01Icon as React.ElementType,
  UserMultiple02: HI.UserMultiple02Icon as React.ElementType,
  UserRemove01: HI.UserRemove01Icon as React.ElementType,
  UserSearch01: HI.UserSearch01Icon as React.ElementType,
  UserStory: HI.UserStoryIcon as React.ElementType,
  UserUnlock01: HI.UserUnlock01Icon as React.ElementType,
  VideoConsole: HI.VideoConsoleIcon as React.ElementType,
  VideoReplay: HI.VideoReplayIcon as React.ElementType,
  Voice: HI.VoiceIcon as React.ElementType,
  VoiceId: HI.VoiceIdIcon as React.ElementType,
  VolumeOff: HI.VolumeOffIcon as React.ElementType,
  Wallet02: HI.Wallet02Icon as React.ElementType,
  WalletAdd01: HI.WalletAdd01Icon as React.ElementType,
  WalletDone01: HI.WalletDone01Icon as React.ElementType,
  WalletNotFound01: HI.WalletNotFound01Icon as React.ElementType,
  WalletRemove01: HI.WalletRemove01Icon as React.ElementType,
  Watch01: HI.Watch01Icon as React.ElementType,
  WaterEnergy: HI.WaterEnergyIcon as React.ElementType,
  WaterPolo: HI.WaterPoloIcon as React.ElementType,
  WaterPump: HI.WaterPumpIcon as React.ElementType,
  WaterfallDown01: HI.WaterfallDown01Icon as React.ElementType,
  WaterfallUp01: HI.WaterfallUp01Icon as React.ElementType,
  Watermelon: HI.WatermelonIcon as React.ElementType,
  WebDesign01: HI.WebDesign01Icon as React.ElementType,
  WebProgramming: HI.WebProgrammingIcon as React.ElementType,
  WebProtection: HI.WebProtectionIcon as React.ElementType,
  WebSecurity: HI.WebSecurityIcon as React.ElementType,
  WebValidation: HI.WebValidationIcon as React.ElementType,
  Webflow: HI.WebflowIcon as React.ElementType,
  WebflowEllipse: HI.WebflowEllipseIcon as React.ElementType,
  WebflowRectangle: HI.WebflowRectangleIcon as React.ElementType,
  Webhook: HI.WebhookIcon as React.ElementType,
  Weight: HI.WeightIcon as React.ElementType,
  WeightScale01: HI.WeightScale01Icon as React.ElementType,
  Wheelchair: HI.WheelchairIcon as React.ElementType,
  WifiCircle: HI.WifiCircleIcon as React.ElementType,
  WifiConnected01: HI.WifiConnected01Icon as React.ElementType,
  WifiDisconnected01: HI.WifiDisconnected01Icon as React.ElementType,
  WifiError01: HI.WifiError01Icon as React.ElementType,
  WifiFullSignal: HI.WifiFullSignalIcon as React.ElementType,
  WifiLocation: HI.WifiLocationIcon as React.ElementType,
  WifiLock: HI.WifiLockIcon as React.ElementType,
  WifiLowSignal: HI.WifiLowSignalIcon as React.ElementType,
  WifiMediumSignal: HI.WifiMediumSignalIcon as React.ElementType,
  WifiNoSignal: HI.WifiNoSignalIcon as React.ElementType,
  WifiOff01: HI.WifiOff01Icon as React.ElementType,
  WifiSquare: HI.WifiSquareIcon as React.ElementType,
  WifiUnlock: HI.WifiUnlockIcon as React.ElementType,
  WindPower01: HI.WindPower01Icon as React.ElementType,
  WindSurf: HI.WindSurfIcon as React.ElementType,
  WindTurbine: HI.WindTurbineIcon as React.ElementType,
  Wireless: HI.WirelessIcon as React.ElementType,
  WirelessCloudAccess: HI.WirelessCloudAccessIcon as React.ElementType,
  Woman: HI.WomanIcon as React.ElementType,
  Wrench01: HI.Wrench01Icon as React.ElementType,
  Wrench02: HI.Wrench02Icon as React.ElementType,
  Xls01: HI.Xls01Icon as React.ElementType,
  Yoga01: HI.Yoga01Icon as React.ElementType,
  YogaBall: HI.YogaBallIcon as React.ElementType,
  YogaMat: HI.YogaMatIcon as React.ElementType,
  Zip01: HI.Zip01Icon as React.ElementType,
  Zoom: HI.ZoomIcon as React.ElementType,
  ZoomCircle: HI.ZoomCircleIcon as React.ElementType,
  ZoomInArea: HI.ZoomInAreaIcon as React.ElementType,
  ZoomOutArea: HI.ZoomOutAreaIcon as React.ElementType,
  ZoomSquare: HI.ZoomSquareIcon as React.ElementType,
};

interface IconPickerProps {
  currentIcon: string;
  onSelect: (iconName: string) => void;
  onClose: () => void;
  onRemove?: () => void;
}

export function IconPicker({ currentIcon, onSelect, onClose, onRemove }: IconPickerProps) {
  const [search, setSearch] = useState('');
  const [recentIcons, setRecentIcons] = useState<string[]>(() => {
    if (typeof window === 'undefined') return [];
    try {
      const savedIcons = JSON.parse(window.localStorage.getItem(RECENT_ICONS_STORAGE_KEY) || '[]');
      return Array.isArray(savedIcons)
        ? savedIcons.filter((name): name is string => typeof name === 'string' && !!ALL_ICONS[name]).slice(0, MAX_RECENT_ICONS)
        : [];
    } catch {
      return [];
    }
  });

  const filteredIcons = Object.entries(ALL_ICONS).filter(([name]) => 
    name.toLowerCase().includes(search.toLowerCase())
  );
  const visibleRecentIcons = useMemo(
    () => [currentIcon, ...recentIcons.filter(name => name !== currentIcon)]
      .filter(name => !!ALL_ICONS[name])
      .slice(0, MAX_RECENT_ICONS)
      .map(name => [name, ALL_ICONS[name]] as const),
    [currentIcon, recentIcons]
  );

  const saveRecentIcon = (iconName: string) => {
    const nextRecentIcons = [iconName, ...recentIcons.filter(name => name !== iconName)].slice(0, MAX_RECENT_ICONS);
    setRecentIcons(nextRecentIcons);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(RECENT_ICONS_STORAGE_KEY, JSON.stringify(nextRecentIcons));
    }
  };

  const handleSelect = (iconName: string) => {
    saveRecentIcon(iconName);
    onSelect(iconName);
  };

  const handleRandomize = () => {
    const names = Object.keys(ALL_ICONS);
    const randomName = names[Math.floor(Math.random() * names.length)];
    handleSelect(randomName);
  };

  return (
    <div className="flex flex-col w-64 bg-[var(--tokyo-panel)] border border-[var(--tokyo-border-strong)] rounded-xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-100">
      <div className="flex items-center justify-between px-3 py-2 border-b border-[var(--tokyo-border)]">
        <div className="text-xs font-medium text-[var(--tokyo-text-muted)]">Icons</div>
        {onRemove && (
          <button 
            onClick={onRemove}
            className="text-xs font-medium text-[var(--tokyo-text-faint)] hover:text-[var(--tokyo-pink)] transition-colors cursor-pointer"
          >
            Remove
          </button>
        )}
      </div>
      <div className="p-2 flex gap-1.5">
        <div className="relative flex-1">
          <HI.Search01Icon className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-[var(--tokyo-text-faint)]" />
          <input 
            type="text"
            placeholder="Search..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-8 w-full rounded-md border border-[var(--tokyo-border-strong)] bg-transparent py-1 pl-8 pr-2 !text-[13px] leading-none text-[var(--tokyo-text-strong)] placeholder:!text-[13px] placeholder:text-[var(--tokyo-text-faint)] focus:border-[var(--tokyo-border-strong)] focus:outline-none focus:ring-0"
            autoFocus
          />
        </div>
        <button 
          onClick={handleRandomize}
          className="h-8 w-8 rounded-md border border-[var(--tokyo-border-strong)] bg-transparent text-[var(--tokyo-text-faint)] hover:text-[var(--tokyo-text)] hover:bg-[var(--tokyo-hover)] transition-colors cursor-pointer flex items-center justify-center"
          title="Randomize"
        >
          <HI.ShuffleIcon className="w-3.5 h-3.5" />
        </button>
      </div>
      <div className="flex-1 overflow-y-auto max-h-[280px] p-2 scrollbar-hide">
        {!search && visibleRecentIcons.length > 0 && (
          <div className="mb-2 border-b border-[var(--tokyo-border)] pb-2">
            <div className="px-1 pb-1.5 text-[10px] font-medium uppercase tracking-[0.08em] text-[var(--tokyo-text-faint)]">
              Recent
            </div>
            <div className="grid grid-cols-6 gap-0.5">
              {visibleRecentIcons.map(([name, Icon]) => (
                <button
                  key={name}
                  onClick={() => handleSelect(name)}
                  className="p-1.5 rounded-md flex items-center justify-center text-[var(--tokyo-text-faint)] transition-all hover:bg-[var(--tokyo-hover)] hover:text-[var(--tokyo-text)] cursor-pointer"
                  title={name}
                >
                  <Icon className="w-4 h-4 stroke-[1.5]" />
                </button>
              ))}
            </div>
          </div>
        )}
        <div className="grid grid-cols-6 gap-0.5">
          {filteredIcons.map(([name, Icon]) => (
            <button
              key={name}
              onClick={() => handleSelect(name)}
              className={cn(
                "p-1.5 rounded-md flex items-center justify-center transition-all cursor-pointer",
                currentIcon === name ? "bg-[var(--tokyo-yellow-dim)] text-[var(--tokyo-text-strong)]" : "text-[var(--tokyo-text-faint)] hover:bg-[var(--tokyo-hover)] hover:text-[var(--tokyo-text)]"
              )}
              title={name}
            >
              <Icon className="w-4 h-4 stroke-[1.5]" />
            </button>
          ))}
        </div>
        {filteredIcons.length === 0 && (
          <div className="flex flex-col items-center justify-center py-8 text-white/10">
            <HI.Search01Icon className="w-8 h-8 mb-1 opacity-5" />
            <p className="text-xs">No icons found</p>
          </div>
        )}
      </div>
    </div>
  );
}
